"""create schema

Revision ID: 7b68506b7d08
Revises:
Create Date: 2026-04-03 12:52:48.109911

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from infra.postgres.tables import (
    blocks_table,
    node_connections_table,
    node_layouts_table,
    platforms_table,
    stations_table,
    vehicles_table,
)
from infra.seed import (
    create_blocks,
    create_connections,
    create_node_layouts,
    create_stations,
    create_vehicles,
)
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7b68506b7d08"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blocks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("group", sa.Integer(), nullable=False),
        sa.Column("traversal_time_seconds", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "node_connections",
        sa.Column("from_id", sa.Uuid(), nullable=False),
        sa.Column("to_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("from_id", "to_id"),
    )
    op.create_table(
        "node_layouts",
        sa.Column("node_id", sa.Uuid(), nullable=False),
        sa.Column("x", sa.Float(), nullable=False),
        sa.Column("y", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("node_id"),
    )
    op.create_table(
        "stations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("is_yard", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "vehicles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "platforms",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("station_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["station_id"],
            ["stations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "services",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("vehicle_id", sa.Uuid(), nullable=False),
        sa.Column("route", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("timetable", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###

    # Seed reference data
    conn = op.get_bind()

    stations = create_stations()
    conn.execute(
        stations_table.insert(),
        [{"id": s.id, "name": s.name, "is_yard": s.is_yard} for s in stations],
    )

    platform_rows = [
        {"id": p.id, "name": p.name, "station_id": s.id}
        for s in stations
        for p in s.platforms
    ]
    if platform_rows:
        conn.execute(platforms_table.insert(), platform_rows)

    blocks = create_blocks()
    conn.execute(
        blocks_table.insert(),
        [
            {
                "id": b.id,
                "name": b.name,
                "group": b.group,
                "traversal_time_seconds": b.traversal_time_seconds,
            }
            for b in blocks
        ],
    )

    vehicles = create_vehicles()
    conn.execute(
        vehicles_table.insert(),
        [{"id": v.id, "name": v.name} for v in vehicles],
    )

    connections = create_connections()
    conn.execute(
        node_connections_table.insert(),
        [{"from_id": c.from_id, "to_id": c.to_id} for c in connections],
    )

    layouts = create_node_layouts()
    conn.execute(
        node_layouts_table.insert(),
        [{"node_id": nid, "x": x, "y": y} for nid, (x, y) in layouts.items()],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("services")
    op.drop_table("platforms")
    op.drop_table("vehicles")
    op.drop_table("stations")
    op.drop_table("node_layouts")
    op.drop_table("node_connections")
    op.drop_table("blocks")
    # ### end Alembic commands ###
